# CONFIGURACION MULTIPART (Carga DE ARCHIVOS)
spring.servlet.multipart.enabled=true
# Directorio intermedio para subir archivos 
spring.servlet.multipart.location=c:/tmp
# Maximo tamaño del archivo a subir
spring.servlet.multipart.max-file-size=2MB
app.ruta.imagenes=C:/RepositorioPrograWeb/thyme8/src/main/resources/static/images/

spring.resources.static-locations= /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:///C:/backup/
